export function mathHelper1(x) { return x + 1; }
export function mathHelper2(x) { return x + 2; }
export function mathHelper3(x) { return x + 3; }
export function mathHelper4(x) { return x + 4; }
export function mathHelper5(x) { return x + 5; }
export function mathHelper6(x) { return x + 6; }
export function mathHelper7(x) { return x + 7; }
export function mathHelper8(x) { return x + 8; }
export function mathHelper9(x) { return x + 9; }
export function mathHelper10(x) { return x + 10; }
export function mathHelper11(x) { return x + 11; }
export function mathHelper12(x) { return x + 12; }
export function mathHelper13(x) { return x + 13; }
export function mathHelper14(x) { return x + 14; }
export function mathHelper15(x) { return x + 15; }
export function mathHelper16(x) { return x + 16; }
export function mathHelper17(x) { return x + 17; }
export function mathHelper18(x) { return x + 18; }
export function mathHelper19(x) { return x + 19; }
export function mathHelper20(x) { return x + 20; }
export function mathHelper21(x) { return x + 21; }
export function mathHelper22(x) { return x + 22; }
