export function validationHelper1(x) { return typeof x === 'number' && x > 1; }
export function validationHelper2(x) { return typeof x === 'number' && x > 2; }
export function validationHelper3(x) { return typeof x === 'number' && x > 3; }
export function validationHelper4(x) { return typeof x === 'number' && x > 4; }
export function validationHelper5(x) { return typeof x === 'number' && x > 5; }
export function validationHelper6(x) { return typeof x === 'number' && x > 6; }
export function validationHelper7(x) { return typeof x === 'number' && x > 7; }
export function validationHelper8(x) { return typeof x === 'number' && x > 8; }
export function validationHelper9(x) { return typeof x === 'number' && x > 9; }
export function validationHelper10(x) { return typeof x === 'number' && x > 10; }
export function validationHelper11(x) { return typeof x === 'number' && x > 11; }
export function validationHelper12(x) { return typeof x === 'number' && x > 12; }
export function validationHelper13(x) { return typeof x === 'number' && x > 13; }
export function validationHelper14(x) { return typeof x === 'number' && x > 14; }
export function validationHelper15(x) { return typeof x === 'number' && x > 15; }
export function validationHelper16(x) { return typeof x === 'number' && x > 16; }
export function validationHelper17(x) { return typeof x === 'number' && x > 17; }
export function validationHelper18(x) { return typeof x === 'number' && x > 18; }
export function validationHelper19(x) { return typeof x === 'number' && x > 19; }
export function validationHelper20(x) { return typeof x === 'number' && x > 20; }
export function validationHelper21(x) { return typeof x === 'number' && x > 21; }
export function validationHelper22(x) { return typeof x === 'number' && x > 22; }
export function validationHelper23(x) { return typeof x === 'number' && x > 23; }
