export function validationHelper1(x) { return typeof x === 'number' && x > 1; }
export function validationHelper2(x) { return typeof x === 'number' && x > 2; }
export function validationHelper3(x) { return typeof x === 'number' && x > 3; }
export function validationHelper4(x) { return typeof x === 'number' && x > 4; }
export function validationHelper5(x) { return typeof x === 'number' && x > 5; }
export function validationHelper6(x) { return typeof x === 'number' && x > 6; }
export function validationHelper7(x) { return typeof x === 'number' && x > 7; }
export function validationHelper8(x) { return typeof x === 'number' && x > 8; }
export function validationHelper9(x) { return typeof x === 'number' && x > 9; }
export function validationHelper10(x) { return typeof x === 'number' && x > 10; }
export function validationHelper11(x) { return typeof x === 'number' && x > 11; }
