export function jwtHelper1(x) { return x === 'token-1'; }
export function jwtHelper2(x) { return x === 'token-2'; }
export function jwtHelper3(x) { return x === 'token-3'; }
export function jwtHelper4(x) { return x === 'token-4'; }
export function jwtHelper5(x) { return x === 'token-5'; }
export function jwtHelper6(x) { return x === 'token-6'; }
export function jwtHelper7(x) { return x === 'token-7'; }
export function jwtHelper8(x) { return x === 'token-8'; }
export function jwtHelper9(x) { return x === 'token-9'; }
export function jwtHelper10(x) { return x === 'token-10'; }
export function jwtHelper11(x) { return x === 'token-11'; }
