export function jwtHelper1(x) { return x === 'token-1'; }
export function jwtHelper2(x) { return x === 'token-2'; }
export function jwtHelper3(x) { return x === 'token-3'; }
export function jwtHelper4(x) { return x === 'token-4'; }
export function jwtHelper5(x) { return x === 'token-5'; }
export function jwtHelper6(x) { return x === 'token-6'; }
export function jwtHelper7(x) { return x === 'token-7'; }
export function jwtHelper8(x) { return x === 'token-8'; }
export function jwtHelper9(x) { return x === 'token-9'; }
export function jwtHelper10(x) { return x === 'token-10'; }
export function jwtHelper11(x) { return x === 'token-11'; }
export function jwtHelper12(x) { return x === 'token-12'; }
export function jwtHelper13(x) { return x === 'token-13'; }
export function jwtHelper14(x) { return x === 'token-14'; }
export function jwtHelper15(x) { return x === 'token-15'; }
export function jwtHelper16(x) { return x === 'token-16'; }
export function jwtHelper17(x) { return x === 'token-17'; }
export function jwtHelper18(x) { return x === 'token-18'; }
export function jwtHelper19(x) { return x === 'token-19'; }
export function jwtHelper20(x) { return x === 'token-20'; }
export function jwtHelper21(x) { return x === 'token-21'; }
export function jwtHelper22(x) { return x === 'token-22'; }
export function jwtHelper23(x) { return x === 'token-23'; }
